---

- name: getblockchaininfo
  command: dash-cli {{ faucet_rpc_args }} getblockchaininfo
  when: num_blocks|int > 0
  register: getblockchaininfo_result

- set_fact:
    initial_block_count: "{{ (getblockchaininfo_result.stdout|from_json).blocks|int }}"
  when: num_blocks|int > 0

- debug: var=initial_block_count
  when: num_blocks|int > 0

- name: wait for {{ num_blocks }} blocks
  command: dash-cli {{ faucet_rpc_args }} getblockchaininfo
  when: num_blocks|int > 0
  register: getblockchaininfo_result
  until: (getblockchaininfo_result.stdout|from_json).blocks|int >= (initial_block_count|int + num_blocks|int)
  retries: 200
  delay: 10

- name: wait for enough blocks to have {{ balance_needed|default(0) }} coins
  command: dash-cli {{ faucet_rpc_args }} getbalance
  when: balance_needed|float > 0
  register: balance_result
  until: balance_result.stdout|float >= balance_needed|float
  retries: 200
  delay: 10

- set_fact:
    new_balance: "{{ balance_result.stdout|float }}"
  when: balance_needed|float > 0
