---

filebeat_inputs:
  - type: container
    enabled: "{{ core_host_info.containers | length > 0 }}"
    index: "logs-core-{{ dash_network_name }}-%{[agent.version]}"
    paths:
      - '/var/lib/docker/containers/{{ core_container_id }}/*.log'
    processors:
      - add_fields:
          target: event
          fields:
            dataset: "core-{{ dash_network_name }}"
      - dissect:
          tokenizer: "%{?timestamp} %{message}"
          overwrite_keys: true
          target_prefix: ""
