---

- name: Fund collateral for {{ payment_target }}
  ansible.builtin.command: >
    dash-cli -rpcwallet={{ wallet_rpc_wallet_faucet }} sendtoaddress {{ payment_target }} {{ amount }}
  register: fund_result
  changed_when: fund_result.stdout | length == 64

- name: Confirm collateral funding for {{ payment_target }}
  ansible.builtin.include_role:
    name: generate_blocks
  vars:
    generate: confirmations
    txid_list: "{{ [fund_result.stdout] }}"
    tx_source: "{{ wallet_rpc_wallet_faucet }}"
  when: fund_result.stdout is defined and fund_result.stdout | length > 0
