---

# Requires "payment_targets" and "amount" variables

- name: Initialize array for payments
  ansible.builtin.set_fact:
    payments: []

- name: Populate payment addresses and values
  ansible.builtin.set_fact:
    payments: "{{ payments | default({}) | combine({item: amount}) }}"
  with_items:
    - '{{ payment_targets }}'

- name: Show list of payments to be made
  ansible.builtin.debug:
    var: payments

- name: Initialize list of collateral funding txids
  ansible.builtin.set_fact:
    fund_txids: []

- name: Fund listed masternodes with {{ amount ~ ' Dash' }}
  ansible.builtin.command:
    argv:
      - dash-cli
      - "-rpcwallet={{ wallet_rpc_wallet_faucet }}"
      - sendtoaddress
      - "{{ item.key }}"
      - "{{ item.value | string }}"
  register: fund_result
  changed_when: (fund_result.stdout | default('') | length) == 64
  with_dict: "{{ payments }}"

- name: Collect collateral funding txids
  ansible.builtin.set_fact:
    fund_txids: "{{ fund_txids + [item.stdout] }}"
  with_items: "{{ fund_result.results }}"
  when: (item.stdout | default('') | length) == 64

- name: Produce blocks until funding transaction is confirmed
  ansible.builtin.include_role:
    name: generate_blocks
  vars:
    generate: confirmations
    txid_list: "{{ fund_txids }}"
    tx_source: "{{ wallet_rpc_wallet_faucet }}"
