---

- name: Set vars
  ansible.builtin.set_fact:
    dashmate_zerossl_keys_path: "{{ dashmate_config_dir }}/{{ dash_network_name }}/platform/gateway/ssl"
    dashmate_zerossl_config_path: "platform.gateway.ssl.providerConfigs.zerossl"
    dashmate_zerossl_csr_file_name: "csr.pem"
    dashmate_zerossl_private_key_file_name: "private.key"
    dashmate_zerossl_bundle_file_name: "bundle.crt"

- name: Create dashmate ssl directory
  ansible.builtin.file:
    path: '{{ dashmate_zerossl_keys_path }}'
    state: directory
    owner: '{{ dashmate_user }}'
    group: '{{ dashmate_group }}'
    mode: "0750"

# Set certificate ID to dashmate config

- name: Get ZeroSSL certificate ID from network config
  ansible.builtin.set_fact:
    dashmate_zerossl_certificate_id: "{{ (hp_masternodes[inventory_hostname]['zerossl_certificate_id'] | default('')) if hp_masternodes is defined and inventory_hostname in (hp_masternodes | default({})) else '' }}"

- name: Set ZeroSSL certificate ID to dashmate config if not set
  ansible.builtin.command: "{{ dashmate_cmd }} config set {{ dashmate_zerossl_config_path }}.id {{ dashmate_zerossl_certificate_id }}"
  become: true
  become_user: dashmate
  args:
    chdir: '{{ dashmate_cwd }}'
  register: dashmate_zerossl_id
  changed_when: dashmate_zerossl_id.rc == 0
  when:
    - dashmate_zerossl_certificate_id != ''
    - dashmate_zerossl_config_certificate_id is not defined

# Create a new ZeroSSL certificate if it is not present
# or download bundle if it doesn't exist

- name: Check that ZeroSSL bundle file exists
  ansible.builtin.stat:
    path: '{{ dashmate_zerossl_keys_path }}/{{ dashmate_zerossl_bundle_file_name }}'
  register: zero_ssl_bundle_file

- name: Obtain ZeroSSL certificate for DAPI
  ansible.builtin.command: "{{ dashmate_cmd }} ssl obtain --verbose --no-retry"
  become: true
  become_user: dashmate
  args:
    chdir: '{{ dashmate_cwd }}'
  register: dashmate_obtain
  changed_when: dashmate_obtain.rc == 0
  when: >
    dashmate_zerossl_certificate_id == '' or
    not zero_ssl_bundle_file.stat.exists