---

- name: Check if logs directory exists
  ansible.builtin.stat:
    path: '{{ dashmate_logs_dir }}'
  register: logs_dir_stat

- name: Create logs dir
  ansible.builtin.file:
    path: '{{ dashmate_logs_dir }}'
    state: directory
    owner: '{{ dashmate_user }}'
    group: '{{ dashmate_group }}'
    recurse: true
  when: not logs_dir_stat.stat.exists

- name: Ensure logs dir has correct ownership
  ansible.builtin.file:
    path: '{{ dashmate_logs_dir }}'
    state: directory
    owner: '{{ dashmate_user }}'
    group: '{{ dashmate_group }}'
    recurse: true

- name: Check if logrotate config exists
  ansible.builtin.stat:
    path: /etc/logrotate.d/platform-logs
  register: logrotate_stat

- name: Configure log rotation
  ansible.builtin.copy:
    dest: /etc/logrotate.d/platform-logs
    content: |
      {{ dashmate_logs_dir }}/*.log {
          rotate 7
          daily
          maxsize 1G
          missingok
          notifempty
          copytruncate
          compress
          delaycompress
      }
    owner: root
    group: root
    mode: '0644'
  when: not logrotate_stat.stat.exists or force_logrotate_config | default(false)

- name: Check if logrotate timer is already hourly
  ansible.builtin.command: grep -q '^OnCalendar=hourly' /lib/systemd/system/logrotate.timer
  register: logrotate_timer_check
  failed_when: false
  changed_when: false

- name: Ensure logrotate runs hourly under systemd timer
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/logrotate.timer
    regexp: '^OnCalendar=hourly'
    insertafter: '^OnCalendar=daily'
    line: OnCalendar=hourly
  when: logrotate_timer_check.rc != 0

- name: Load common filebeat config
  ansible.builtin.include_vars:
    file: "{{ role_path }}/../core_filebeat/vars/common.yml"

- name: Load filebeat inputs
  ansible.builtin.include_vars:
    file: filebeat_inputs.yml

- name: Set facts for filebeat role (assume Ubuntu/Debian)
  ansible.builtin.set_fact:
    ansible_os_family: "Debian"
    ansible_distribution: "Ubuntu"
    ansible_distribution_major_version: "22"
    ansible_pkg_mgr: "apt"

- name: Set up filebeat log monitoring
  ansible.builtin.include_role:
    name: geerlingguy.filebeat

- name: Check if filebeat configuration changed
  ansible.builtin.set_fact:
    filebeat_config_changed: "{{ filebeat_config_file_result is defined and filebeat_config_file_result.changed }}"

- name: Make sure filebeat is restarted
  ansible.builtin.service:
    name: filebeat
    state: restarted
    enabled: true
  when: filebeat_config_changed | default(false) or force_filebeat_restart | default(false)
