---

- name: Restart dashmate services for current chunk
  ansible.builtin.command: "{{ dashmate_cmd }} restart --safe --verbose{{ '' if needs_core_restart | default(false) else ' --platform' }}"
  become: true
  become_user: dashmate
  become_flags: '-H'
  args:
    chdir: '{{ dashmate_cwd }}'
  register: dashmate_restart_all
  changed_when: dashmate_restart_all.rc == 0
  delegate_to: "{{ item }}"
  with_items: "{{ current_chunk }}"

- name: Print progress
  ansible.builtin.debug:
    msg: "Restarted chunk {{ current_chunk_index + 1 }} of {{ host_chunks | length }}"

- name: Wait for delay before restarting next chunk
  ansible.builtin.wait_for:
    timeout: "{{ (restart_delay_minutes | default(1)) * 60 }}"
  delegate_to: localhost
  run_once: true
  when: current_chunk_index + 1 < host_chunks|length
