---

- name: Add the official ET repository
  ansible.builtin.apt_repository:
    repo: ppa:jgmath2000/et
    state: present
    update_cache: true
  register: et_repo
  retries: 5
  delay: 20
  until: et_repo is succeeded

- name: Install ET
  ansible.builtin.package:
    name: et
    state: present
