---

- name: Build Dash Network common base image
  hosts: all
  become: true
  gather_facts: true
  vars:
    swap_space: 2G
    pip_package: python3-pip
    pip_install_packages:
      - name: docker
        version: "6.0.1"
      - name: docker-compose
        version: "1.29.2"
      - name: requests
        version: "2.31.0"
  pre_tasks:
    - name: Update apt cache and install common packages
      ansible.builtin.apt:
        pkg:
          - acl
          - jq
          - unzip
        update_cache: true
  roles:
    - swap
    - geerlingguy.pip
    - role: geerlingguy.docker
      vars:
        docker_apt_arch: "{{ 'amd64' if ansible_facts['architecture'] == 'x86_64' else 'arm64' }}"
        docker_install_compose: false
        docker_users:
          - ubuntu
    - docker_options
    - eternal_terminal
